apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: my-pt-pvc
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 3Gi
    selector:
        matchLabels:
            type: myptpv
