apiVersion: v1
kind: PersistentVolume
metadata:
    name: my-pt-log-pv
    labels:
        type: myptpv
spec:
    capacity:
        storage: 10Gi
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: "/mnt/logs"
