apiVersion: v1
kind: PersistentVolume
metadata:
    name: uptime-kuma-pv
    namespace: uptime-kuma
    labels:
        type: uptimekuma
spec:
    accessModes:
        - ReadWriteOnce
    capacity:
        storage: 10Gi
    persistentVolumeReclaimPolicy: Retain
    hostPath:
        path: "/mnt/kuma"
