apiVersion: batch/v1
kind: CronJob
metadata:
    name: php-harvest-download
spec:
    schedule: "*/30 * * * *"
    suspend: false
    jobTemplate:
        spec:
            template:
                spec:
                    containers:
                        - name: php-container
                          image: 192.168.1.245:32000/my-portfolio-tracker-php:1.25
                          command: ["sh", "-c", "cd /var && COMPOSER_ALLOW_SUPERUSER=1 php composer.phar harvest-download"]
                          volumeMounts:
                              - name: log-data
                                mountPath: /var/log
                    restartPolicy: OnFailure
                    volumes:
                        - name: log-data
                          persistentVolumeClaim:
                              claimName: my-pt-log-pvc

---

apiVersion: batch/v1
kind: CronJob
metadata:
    name: php-download-all-data
spec:
    schedule: "35,40,45 12,16,22 * * MON-FRI"
    suspend: false
    jobTemplate:
        spec:
            template:
                spec:
                    containers:
                        - name: php-container
                          image: 192.168.1.245:32000/my-portfolio-tracker-php:1.25
                          command: ["sh", "-c", "cd /var && COMPOSER_ALLOW_SUPERUSER=1 php composer.phar download-all"]
                          volumeMounts:
                              - name: log-data
                                mountPath: /var/log
                    restartPolicy: OnFailure
                    volumes:
                        - name: log-data
                          persistentVolumeClaim:
                              claimName: my-pt-log-pvc

---

apiVersion: batch/v1
kind: CronJob
metadata:
    name: php-download-dividends
spec:
    schedule: "0 6 * * 1,3,5"
    suspend: false
    jobTemplate:
        spec:
            template:
                spec:
                    containers:
                        - name: php-container
                          image: 192.168.1.245:32000/my-portfolio-tracker-php:1.25
                          command: ["sh", "-c", "cd /var && COMPOSER_ALLOW_SUPERUSER=1 php composer.phar download-dividends"]
                          volumeMounts:
                              - name: log-data
                                mountPath: /var/log
                    restartPolicy: OnFailure
                    volumes:
                        - name: log-data
                          persistentVolumeClaim:
                              claimName: my-pt-log-pvc

---

apiVersion: batch/v1
kind: CronJob
metadata:
    name: php-save-current-portfolio-statistics
spec:
    schedule: "0 10 * * *"
    suspend: false
    jobTemplate:
        spec:
            template:
                spec:
                    containers:
                        - name: php-container
                          image: 192.168.1.245:32000/my-portfolio-tracker-php:1.25
                          command: ["sh", "-c", "cd /var && COMPOSER_ALLOW_SUPERUSER=1 php composer.phar save-current-portfolio-statistics"]
                          volumeMounts:
                              - name: log-data
                                mountPath: /var/log
                    restartPolicy: OnFailure
                    volumes:
                        - name: log-data
                          persistentVolumeClaim:
                              claimName: my-pt-log-pvc
