apiVersion: apps/v1
kind: Deployment
metadata:
    name: mariadb
spec:
    selector:
        matchLabels:
            app: mariadb
    strategy:
        type: Recreate
    template:
        metadata:
            labels:
                app: mariadb
        spec:
            containers:
                - image: localhost:32000/my-mariadb:1.0
                  name: mariadb
                  env:
                      - name: MYSQL_ROOT_PASSWORD
                        value: my-secret-pw
                  ports:
                      - containerPort: 3306
                        name: mariadb
                  volumeMounts:
                      - name: mariadb-storage
                        mountPath: /var/lib/mysql
            volumes:
                - name: mariadb-storage
                  persistentVolumeClaim:
                      claimName: mariadb-pvc
