apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: uptime-kuma
    namespace: uptime-kuma
spec:
    serviceName: "uptime-kuma"
    replicas: 1
    selector:
        matchLabels:
            app: uptime-kuma
    template:
        metadata:
            labels:
                app: uptime-kuma
        spec:
            containers:
                - name: uptime-kuma
                  image: louislam/uptime-kuma:1
                  imagePullPolicy: IfNotPresent
                  ports:
                      - containerPort: 3001
                        name: web-ui
                  resources:
                      limits:
                          cpu: 200m
                          memory: 512Mi
                      requests:
                          cpu: 50m
                          memory: 128Mi
                  livenessProbe:
                      tcpSocket:
                          port: web-ui
                      initialDelaySeconds: 60
                      periodSeconds: 10
                  readinessProbe:
                      httpGet:
                          scheme: HTTP
                          path: /
                          port: web-ui
                      initialDelaySeconds: 30
                      periodSeconds: 10
                  volumeMounts:
                      - name: data
                        mountPath: /app/data
            volumes:
                - name: data
                  persistentVolumeClaim:
                      claimName: uptime-kuma-pvc
